[global]
developmentMode = true

[browser]
serverAddress = "0.0.0.0"
serverPort = 8501
gatherUsageStats = false

[server]
headless = true
enableCORS=false
enableXsrfProtection=false


[browser]
windowTitle = "헬라어공부방"